### ISSUE TITLE
GRPC Dart client files generated with protoc.exe with error The method 'pc' isn't defined for the class 'BuilderInfo'.

### ISSUE THREAD

**Issue by kamilk91** [grpc/grpc-dart#218]
Error:
```
The method 'pc' isn't defined for the class 'BuilderInfo'.
```
in line:
```
class WUFPersonalDetails extends $pb.GeneratedMessage {
  static final $pb.BuilderInfo _i = $pb.BuilderInfo('WUFPersonalDetails', package: const $pb.PackageName('wufapi'))
    ..pc<WUFResult>(1, 'results', $pb.PbFieldType.PM,WUFResult.create)
    ..hasRequiredFields = false
  ;
```
class generated with protoc.exe with depedencies in yaml 
```
grpc:
protobuf:
```
packages:

```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  camera:
    dependency: "direct main"
    description:
      name: camera
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.2+2"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.11"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.9"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  googleapis_auth:
    dependency: transitive
    description:
      name: googleapis_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.10"
  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.0+2"
  http2:
    dependency: transitive
    description:
      name: http2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.0+17"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.5"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  path:
    dependency: "direct main"
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.2"
  path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  protobuf:
    dependency: "direct main"
    description:
      name: protobuf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.0"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0+1"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.5"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.5"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
sdks:
  dart: ">=2.2.2 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"

```

Compiler message:

```
Compiler message:
lib/GRPC/WUFApi.pb.dart:96:7: Error: The method 'pc' isn't defined for the class 'BuilderInfo'.
 - 'BuilderInfo' is from 'package:protobuf/protobuf.dart' ('file:///C:/Users/kamil/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.11.0/lib/protobuf.dart').
Try correcting the name to the name of an existing method, or defining a method named 'pc'.
    ..pc<WUFResult>(1, 'results', $pb.PbFieldType.PM,WUFResult.create)
      ^^
Compiler failed on C:\git\WhoAreYou\whoareyou\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\kamil\Desktop\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugX86'.

```

**Comment by kamilk91** [comment]
Ok, pub.dev downloaded 0.11.0 version (sic!) randomly when added depedency as
```
protobuf: 
```
i checked [version](https://pub.dev/packages/protobuf#-changelog-tab-) and changed it manualy to latest
```
protobuf: ^0.13.15
```
in **pubspec.yaml** and it works now. 
F*ck my logic, but shouldn't it download latest stable version?!

**Comment by sigurdm** [comment]
> shouldn't it download latest stable version?!

Yes, I think it should.

Could you post the full pubspec.yaml file? I would like to investigate it a bit if I can reproduce.

**Comment by kamilk91** [comment]
@sigurdm 

```
name: Who are you?
description: App gives you response

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  camera:
  path_provider:
  path:
  provider: ^3.0.0+1
  grpc:
  protobuf: ^0.13.15
  image_picker_saver: ^0.3.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  

```
