### ISSUE TITLE
Use URI path in requests

### ISSUE THREAD

**Issue by metalmatze** [grpc/grpc-dart#258]
Hey,
I'd like to pass a URI with a path to the client, so that I can use a proxy in front of my application on the server side to redirect to the correct service.

```dart
final channel = GrpcWebClientChannel.xhr(Uri.parse('http://localhost:6060/grpc'));
```

Now, looking at the source code after trying a couple of things, I can see that the path is simply overwritten by whatever the generated file has.
As of now I am not sure if that's a gRPC requirement or just not implemented in this project.

In line 167 I can see that the path is simply passed into the URI.
https://github.com/grpc/grpc-dart/blob/ae17e712e4f5431eb6664f0589899c77462e5475/lib/src/client/transport/xhr_transport.dart#L164-L167

Part of my pubspec.lock
```yaml
  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
```
