### ISSUE TITLE
[version conflicts] when i use gRPC 3.0.0 on flutter 1.26.0-17.3pre, it can't work

### ISSUE THREAD

**Issue by yang-lile** [grpc/grpc-dart#453]
<version conflicts>

<version of the grpc-dart packages used 3.0.0>

## Repro steps

1. using gRPC ^3.0.0 in the flutter 1.26.0-17.3pre
2. run `flutter pub get`

## Result: 

```powershell
Because every version of flutter_test from sdk depends on meta 1.3.0-nullsafety.6 and grpc >=3.0.0 depends on meta ^1.3.0, flutter_test from sdk is incompatible 
with grpc >=3.0.0.
So, because ddm_client depends on both grpc ^3.0.0 and flutter_test any from sdk, version solving failed.
Running "flutter pub get" in ddm_client...
pub get failed (1; So, because ddm_client depends on both grpc ^3.0.0 and flutter_test any from sdk, version solving failed.)
```

## Details

my main pubspec.yaml file under:
```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^3.24.0
  grpc: ^3.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.16
  permission_handler: ^5.1.0+2
  protobuf: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  hive_generator: ^0.8.2
```

using `any` to get no conflict version, is gRPC ^2.3.0. but I want to use 3.0.0. How could I do?
