### ISSUE TITLE
grpc-web error code: 14, codeName: UNAVAILABLE, message: Missing trailers

### ISSUE THREAD

**Issue by cq-z** [grpc/grpc-dart#505]
<grpc-web error >

 `pubspec.lock` file:
```
  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
```
## Repro steps

1. run this example is ok :https://github.com/fwhat/grpc-demo
![image](https://user-images.githubusercontent.com/3038490/126041260-eef48e6b-0b9d-4d2a-91cc-0d5550bb347c.png)

2. chang client to flutter
```
        final admin = HelloWorldServiceClient(
           GrpcWebClientChannel.xhr(Uri.parse('https://localhost: 8199'))
        );
    try {
    final response = await admin.sayHello(HelloRequest(name: "aa"));
    print(response);
    } catch (error) {
      print(error.toString());
    }
```

Expected result: 
![image](https://user-images.githubusercontent.com/3038490/126041232-f8552bb5-e316-46b6-bc8f-f7e1d8a4bf22.png)

response body is correct
![image](https://user-images.githubusercontent.com/3038490/126041291-ff1abcc6-05ef-4474-9557-2ca8261d458f.png)

**Comment by zhengcan** [comment]
I have the same issue due to using akka-grpc server side.
The grpc-dart throws exception by checking the trailers in https://github.com/grpc/grpc-dart/blob/master/lib/src/client/call.dart#L418

As workaround, I hack the file to skip the checking. After that, my app works well.

**Comment by wb14123** [comment]
Got the same error using akka-grpc and grpc-web with envoy proxy.

**Comment by PlugFox** [comment]
I have similar problem, only with grpc web.

`dart-grpc` on server and client.
`traefik` as reverse proxy and load balancer in docker swarm

Creating client:
```dart
import 'package:grpc/grpc_or_grpcweb.dart' as grpc;

...

final clientChannel = grpc.GrpcOrGrpcWebClientChannel.toSingleEndpoint(
  host: 'api.domain.tld',
  port: 443,
  transportSecure: true,
);
grpc.SomethingServiceClient(
  clientChannel,
  options: grpc.CallOptions(
    timeout: const Duration(minutes: 2),
  ),
);
```

Server side:
```dart
import 'package:grpc/grpc.dart';

...

Server(
  <Service>[
    SomethingService(),
  ],
);
```


Traefik config:
```yml
################################################################
# TRAEFIK CONFIG
traefik.enable: 'true'
traefik.docker.network: traefik-public
traefik.constraint-label: traefik-public

# HTTPS Router
traefik.http.routers.something-router.tls: 'true'
traefik.http.routers.something-router.entrypoints: https
traefik.http.routers.something-router.tls.certresolver: le
traefik.http.routers.something-router.rule: Host(`api.domain.tld`)

# Middlewares
traefik.http.routers.something-router.middlewares: 'something-headers'
# CORS
traefik.http.middlewares.something-headers.headers.accesscontrolallowmethods: GET,PUT,DELETE,POST,OPTIONS
traefik.http.middlewares.something-headers.headers.accesscontrolalloworiginlist: '*'
traefik.http.middlewares.something-headers.headers.accesscontrolexposeheaders: '*'
traefik.http.middlewares.something-headers.headers.accesscontrolallowheaders: '*'
traefik.http.middlewares.something-headers.headers.accesscontrolmaxage: '60'
# Service
traefik.http.routers.something-router.service: something-service
traefik.http.services.something-service.loadbalancer.server.scheme: h2c
traefik.http.services.something-service.loadbalancer.server.port: 9090
################################################################
```

It's working on mobile perfectly, but not working with grpc web.

On the web getting the body is cut off
![image](https://user-images.githubusercontent.com/7805176/140709904-e45f6288-c59e-43fa-aa3c-97422fa61df4.png)

And i have exception like this:
`gRPC Error (code: 14, codeName: UNAVAILABLE, message: Missing trailers, details: null, rawResponse: null, trailers: {})`


Most likely the problem is related to the proxy server and this issue:
https://github.com/traefik/traefik/issues/4210

For me personally, this is not a big problem, since I decided that I would use protobuffs with http 1.1 requests.

And the grpc is only for interservice interaction.

@mraleph 
If the dart team needs any help, I will provide everything that's needed. We can communicate in Russian via telegram.
But most likely the core problem is in the reverse proxy and if you have similar exception you can try Envoy proxy instead traefik.
