### ISSUE TITLE
Help: Invalid frame type: 1

### ISSUE THREAD

**Issue by MateusAmin** [grpc/grpc-dart#506]
```sh
Error: gRPC Error (code: 12, codeName: UNIMPLEMENTED, message: Invalid frame type: 1, details: null, rawResponse: null)
    at Object.throw_ [as throw] (http://localhost:40069/dart_sdk.js:5062:11)
    at web_streams._GrpcWebConversionSink.new.[_parseFrameType] (http://localhost:40069/packages/grpc/src/client/transport/web_streams.dart.lib.js:136:19)
    at web_streams._GrpcWebConversionSink.new.add (http://localhost:40069/packages/grpc/src/client/transport/web_streams.dart.lib.js:209:53)
    at _ConverterStreamEventSink.new.add (http://localhost:40069/dart_sdk.js:45045:29)
    at _SinkTransformerStreamSubscription.new.[_handleData] (http://localhost:40069/dart_sdk.js:36146:34)
    at _RootZone.runUnaryGuarded (http://localhost:40069/dart_sdk.js:37595:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:40069/dart_sdk.js:31475:22)
    at _DelayedData.new.perform (http://localhost:40069/dart_sdk.js:34780:28)
    at _StreamImplEvents.new.handleNext (http://localhost:40069/dart_sdk.js:34884:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:40069/dart_sdk.js:34645:16)
    at Object._microtaskLoop (http://localhost:40069/dart_sdk.js:37925:13)
    at _startMicrotaskLoop (http://localhost:40069/dart_sdk.js:37931:13)
    at http://localhost:40069/dart_sdk.js:33666:9
```
  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"

## Repro steps

Will make a demo repo in the morning tomorrow.

Expected result:  gRPC unary call completes without expectation

Actual result: gRPC unary call completes successfully server side but client throws expectation parsing response (an empty message object).

## Details

enovy config:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          access_log:
            - name: envoy.access_loggers.file
              config:
                path: "/dev/stdout"
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: greeter_service
                  max_grpc_timeout: 0s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router
  clusters:
  - name: greeter_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    # win/mac hosts: Use address: host.docker.internal instead of address: localhost in the line below
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 50051
```

envy boot:
```sh
#! /bin/sh

sudo docker run -it -v "$(pwd)"/envoy.yaml:/etc/envoy/envoy.yaml:ro \
    --network=host envoyproxy/envoy:v1.15.0 --use-dynamic-base-id  --config-path '/etc/envoy/envoy.yaml'
```

dart grpc server:
```sh
#! /bin/sh

shellcheck ./*.sh

cd ../messages || exit
    ./../messages/grpc.sh
cd - || exit

dart bin/server.dart
```

message script
```sh
#! /bin/sh

shellcheck ./*.sh

# mac os specific
# brew install protobuf

dart pub global activate protoc_plugin
export PATH="$PATH:$HOME/.pub-cache/bin"
protoc --dart_out=grpc:lib/src/generated -Iprotos protos/messages.proto
```
