### ISSUE TITLE
Incorrect code generation for `google/protobuf/empty.proto`

### ISSUE THREAD

**Issue by BorzdeG** [grpc/grpc-dart#560]
Some proto files do not generate dart code correctly

pubspec.lock :
```
grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
```

## Repro steps

1. create proto file:

```proto
syntax = "proto3";

package demo;
option go_package = "./demo";

import "google/protobuf/empty.proto";

message DemoResponse {
	string name = 1;
}
service DemoService {
	rpc Say (google.protobuf.Empty) returns (DemoResponse);
}
```

2. generate Dart code: `protoc --proto_path=proto --dart_out=grpc:lib/src/generated demo.proto`

3.  Added Dart dependencies: `dart pub add protobuf http2 grpc`
4. Open `demo.pbgrpc.dart` file

Expected result: All imports are correct

Actual result: 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/2332528/174495614-abb60099-e608-4403-8493-cee5d0a18baf.png">
