### ISSUE TITLE
Any cannot be imported

### ISSUE THREAD

**Issue by TamasBarta** [grpc/grpc-dart#589]
After depending on `grpc` and importing it as well, `Any` is still unavailable.

Version of the grpc-dart packages and protobuf (just in case) used:

```yaml
  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  protobuf:
    dependency: "direct main"
    description:
      name: protobuf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
```

## Repro steps

It's not runtime behaviour, but to put in this format:

1. Depend on `grpc` package (and run `dart pub get`)
1. Try to import `Any`
1. dartls cannot find it.
1. Import `package:protobuf/protobuf.dart` and `package:grpc/grpc.dart` anyway
1. Still cannot find `Any`
1. Try to compile to see if it's a problem with dartls, no luck

Expected result: `Any` should be available after depending on `grpc` in `pubspec.yaml` a

Actual result: `Any` nowhere to be found.

## Details

I'm trying to implement some sort of error handling, and found that `GrpcError`'s details are all `Any`. This is already pretty cumbersome, but I could work around that, and that's understandable why it's like that. I can just use the solution in #461 to get an instance of the concrete message type. The problem is that `Any` can not be imported, and I didn't even find basically anywhere on the internet, most notably the `grpc` package's [API reference documentation](https://pub.dev/documentation/grpc/latest/grpc/grpc-library.html). I believe this is an error.

Right now I could make this work by manually casting it to `dynamic` which is unnecessarily javascriptish (not to hate on it, but I deliberately chose Dart instead), and I'm sure it's not the intended way to do error handling.

I tried `import "google/protobuf/any.proto";` in our proto files to at least have any sort of `Any`, but type checks don't work on it, so I cannot use it to call its methods, not useful for error handling. (Also the proto project itself doesn't depend on it, so wouldn't be a good solution anyway)
